-- SQLite

-- INSERT INTO DEPARTMENT (ID, DEPT, EMP_ID) VALUES (1, 'IT Billing', 1 );
-- INSERT INTO DEPARTMENT (ID, DEPT, EMP_ID) VALUES (2, 'Engineering', 2 );
-- INSERT INTO DEPARTMENT (ID, DEPT, EMP_ID) VALUES (3, 'Finance', 7 );
-- INSERT INTO DEPARTMENT (ID, DEPT, EMP_ID) VALUES (4, 'IT Billing', 1 );
-- INSERT INTO DEPARTMENT (ID, DEPT, EMP_ID) VALUES (5, 'Finance', 7 );



-- SELECT EMP_ID, COMPANY.NAME, DEPT, OLD_COMPANY.NAME
-- FROM COMPANY
-- INNER JOIN DEPARTMENT
-- on COMPANY.ID = DEPARTMENT.ID
-- INNER JOIN OLD_COMPANY
-- ON COMPANY.ID = OLD_COMPANY.ID;




-- SELECT COMPANY.NAME, OLD_COMPANY.AGE
-- FROM COMPANY
-- INNER JOIN OLD_COMPANY
-- ON COMPANY.ID = OLD_COMPANY.ID;



-- DELETE FROM OLD_COMPANY;



-- INSERT INTO OLD_COMPANY(ID, NAME, AGE, ADDRESS, SALARY)
-- SELECT*FROM COMPANY
-- WHERE SALARY >50000;


SELECT COMP.ID, COMP.NAME, COMP.AGE, COMP.SALARY
FROM (SELECT*FROM COMPANY WHERE SALARY > 2000) AS COMP
LEFT OUTER JOIN DEPARTMENT
ON COMP.ID = DEPARTMENT.EMP_ID;



SELECT EMP_ID, NAME, DEPT 
FROM COMPANY

INNER JOIN DEPARTMENT
ON COMPANY.ID = DEPARTMENT.EMP_ID

UNION

SELECT EMP_ID, NAME, DEPT 
FROM COMPANY

LEFT OUTER JOIN DEPARTMENT
ON COMPANY.ID = DEPARTMENT.EMP_ID;

SELECT NAME, ADDRESS,

CASE NAME
WHEN 'Paul' THEN SALARY
WHEN 'David' THEN AGE
ELSE 'ETC'
END AS NAME_CASE
FROM COMPANY;



SELECT NAME, ADDRESS,

CASE
WHEN NAME == 'Smith' THEN SALARY
END AS SALARY,

CASE
WHEN NAME == 'Allen' THEN AGE
END AS NAME_CASE
FROM COMPANY;