-- SQLite

-- INSERT INTO DEPARTMENT (ID, DEPT, EMP_ID) VALUES (1, 'IT Billing', 1 );
-- INSERT INTO DEPARTMENT (ID, DEPT, EMP_ID) VALUES (2, 'Engineering', 2 );
-- INSERT INTO DEPARTMENT (ID, DEPT, EMP_ID) VALUES (3, 'Finance', 7 );
-- INSERT INTO DEPARTMENT (ID, DEPT, EMP_ID) VALUES (4, 'IT Billing', 1 );
-- INSERT INTO DEPARTMENT (ID, DEPT, EMP_ID) VALUES (5, 'Finance', 7 );



SELECT EMP_ID, COMPANY.NAME, DEPT, OLD_COMPANY.NAME
FROM COMPANY
INNER JOIN DEPARTMENT
on COMPANY.ID = DEPARTMENT.ID
INNER JOIN OLD_COMPANY
ON COMPANY.ID = OLD_COMPANY.ID;




SELECT COMPANY.NAME, OLD_COMPANY.AGE
FROM COMPANY
INNER JOIN OLD_COMPANY
ON COMPANY.ID = OLD_COMPANY.ID;



DELETE FROM OLD_COMPANY;



INSERT INTO OLD_COMPANY(ID, NAME, AGE, ADDRESS, SALARY)
SELECT*FROM COMPANY
WHERE SALARY >50000;