-- SQLite
CREATE TABLE COMPANY(
ID REAL NOT NULL,
NAME TEXT NOT NULL,
AGE REAL NOT NULL,
ADDRESS TEXT NULL,
SALARY REAL NULL
);

CREATE TABLE DEPARTMENT(
ID REAL NOT NULL,
DEPT TEXT NOT NULL,
EMP_ID REAL NOT NULL
);

SELECT * FROM lecture_INFORMATION
WHERE ID BETWEEN 2 AND 3;

DROP TABLE COMPANY;

INSERT INTO COMPANY
VALUES(1, 'park', 27, 'dong', 200, 'www.naver.com');

SELECT*FROM COMPANY;

INSERT INTO COMPANY
VALUES(1, 'park', 27, "" ,200);

ALTER TABLE COMPANY RENAME TO OLD_COMPANY;

ALTER TABLE OLD_COMPANY ADD COLUMN 
EMAIL TEXT NULL;

DELETE FROM COMPANY
WHERE ID = 1;

ALTER TABLE COMPANY
RENAME COLUMN ADDRESS TO address;



INSERT INTO COMPANY(ID, NAME, AGE, ADDRESS, SALARY)
VALUES(1, 'Paul', 33, 'California', 20000);

INSERT INTO COMPANY(ID, NAME, AGE, ADDRESS, SALARY)
VALUES(2, 'Allen', 25, 'Texas', 20000);

INSERT INTO COMPANY(ID, NAME, AGE, ADDRESS, SALARY)
VALUES(3, 'Teddy', 23, 'Norway', 20000);

INSERT INTO COMPANY(ID, NAME, AGE, ADDRESS, SALARY)
VALUES(4, 'Mark', 25, 'Rich-Mond', 65000);

INSERT INTO COMPANY(ID, NAME, AGE, ADDRESS, SALARY)
VALUES(5, 'David', 27, 'Texas', 85000);

INSERT INTO COMPANY(ID, NAME, AGE, ADDRESS, SALARY)
VALUES(6, 'Teddy', 23, 'Norway', 20000);



-- 한번에 넣기
INSERT INTO COMPANY(ID, NAME, AGE, ADDRESS, SALARY)
VALUES
(1, 'Paul', 33, 'California', 20000),
(2, 'Allen', 25, 'Texas', 20000),
(3, 'kan', 22, 'Sydney', 50000),
(4, 'Mark', 25, 'Rich-Mond', 65000),
(5, 'David', 27, 'Texas', 85000),
(6, 'Teddy', 23, 'Norway', 20000),
(7, 'Faker', 25, 'Norway', 80000);


-- 테이블 초기화 컬럼은 그대로 있음
DELETE FROM COMPANY;


-- 셀렉트 
SELECT * FROM COMPANY;
SELECT NAME FROM COMPANY
WHERE AGE BETWEEN 25 and 40;
SELECT ID, NAME, SALARY FROM COMPANY;

-- 테이블 이름 가져오기
SELECT tbl_name FROM sqlite_master WHERE type = 'table';

-- sql문 가져오기 테이블 이름이 company인 부분 
SELECT sql FROM sqlite_master
WHERE type = 'table' AND tbl_name = 'COMPANY';

-- 다른 테이블에 값 덮어쓰기 칼럼 매칭 해줘야 됨
INSERT INTO OLD_COMPANY(ID, NAME, AGE, ADDRESS, SALARY)
SELECT ID, NAME, AGE, ADDRESS, SALARY FROM COMPANY;

SELECT*FROM OLD_COMPANY;

-- 조건 걸어서 row 삭제
DELETE FROM OLD_COMPANY
WHERE ID = 1;

-- 중복 제거해서 보기 제거는 아니고 보여줄때만
SELECT DISTINCT * FROM OLD_COMPANY;

-- 값 업데이트 
-- 테이블 이름 변경할 컬럼 = 값 
-- 조건 안 넣으면 전체 업데이트
UPDATE OLD_COMPANY
SET 
EMAIL = 'wnstjd117@naver.com',
SALARY = 880000
WHERE ID = 6;
