-- SQLite
CREATE TABLE COMPANY(
ID REAL NOT NULL,
NAME TEXT NOT NULL,
AGE REAL NOT NULL,
ADDRESS TEXT NULL,
SALARY REAL NULL
);

CREATE TABLE DEPARTMENT(
ID REAL NOT NULL,
DEPT TEXT NOT NULL,
EMP_ID REAL NOT NULL
);

SELECT*FROM lecture_INFORMATION
WHERE ID BETWEEN 2 AND 3;