
        
-- CREATE TABLE COMPANY
-- (
--   COMPANY_ID VARCHAR(100) NOT NULL,
--   NAME       VARCHAR(100) NULL    ,
--   PRIMARY KEY (COMPANY_ID)
-- ) COMMENT '회사';

-- CREATE TABLE DEPARTMENT
-- (
--   ID         VARCHAR(100) NOT NULL,
--   NAME       VARCHAR(100) NULL    ,
--   COMPANY_ID VARCHAR(100) NULL    ,
--   PRIMARY KEY (ID)
-- ) COMMENT '부서';

-- ALTER TABLE DEPARTMENT
--   ADD CONSTRAINT FK_COMPANY_TO_DEPARTMENT
--     FOREIGN KEY (COMPANY_ID)
--     REFERENCES COMPANY (COMPANY_ID);


-- SELECT * FROM `yojulabdb`.`DEPARTMENT` LIMIT 1000;

