-- -- 권한이 ROLE_STUDENT을 가진 목록
-- SELECT * FROM MEMBER
-- INNER JOIN AUTHORITY_MEMBER
-- ON AUTHORITY_MEMBER.MEMBER_SEQ = MEMBER.MEMBER_SEQ
-- WHERE AUTHORITY_MEMBER.AUTHORITY_ID = 'ROLE_STUDENT';


-- -- 강의 강연 조직 구조
-- WITH RECURSIVE TEMP AS(
--     SELECT NAME, PARENT_ORGANIZATION_SEQ, ORGANIZATION_SEQ FROM ORGANIZATION
--     WHERE NAME = '강의/강연 신'
--     UNION
--     SELECT ORGANIZATION.NAME, ORGANIZATION.PARENT_ORGANIZATION_SEQ, ORGANIZATION.ORGANIZATION_SEQ
--     FROM TEMP
--     INNER JOIN ORGANIZATION
--     ON TEMP.ORGANIZATION_SEQ = ORGANIZATION.PARENT_ORGANIZATION_SEQ
-- )
-- SELECT*FROM TEMP;


SELECT*FROM ORGANIZATION_MEMBER;